Bootstrap default QEMU password from VPD
kernelkit/infix pull request #219
Opened 2023-11-22 08:45 UTC by rical

## About
Use default pwd hash from VPD in QEMU.

This PR does several things. Its end goal is to fetch the admin
password hash from VPD memory during factory bootstrap.

To accomplish this probe creates a new file /run/system.json with
information read from a fw_cfg QEMU partition. The data from
/run/system.json is then later used during config bootstrap to fill in
the factory administrator password.

The idea is to make QEMU behave the same way hardware does, i.e. a
default/factory password should be fetched and used from
"hardware memory". The hardware portion of this is yet to be done.

## Future work
There's still a lot to be done in this area. The vendor specific VPD format needs to be established and the fallback flow  during bootstrap needs to be improved. The temporary "hardware fallback hash" needs to be removed and hardware support added.

2023-11-22 09:18 UTC, troglobit approved these changes
Awesome work on this! :clap: 

Edit: the regression tests don't seem too happy though?

2023-11-23 08:14 UTC, troglobit commented
@wkz maybe you can have a quick look at my additions to Richard's VPD support when you get in the office? Really hope I got gist of what we talked about during yesterdays' review.

2023-11-24 07:52 UTC, wkz requested changes

2023-11-24 07:52 UTC, wkz commented on board/common/qemu/qemu.sh
> +      65536,
```suggestion
      61046,
```

This should use Kernelkit's IANA Enterprise Number

2023-11-24 07:52 UTC, wkz commented on board/common/rootfs/lib/infix/probe
> +    fi
This is OK for now. But the real implementation needs to verify the IANA PEN

2023-11-24 07:55 UTC, merged