Add possible to configure USB on/off
kernelkit/infix pull request #302
Opened 2024-02-13 16:07 UTC by mattiaswal

Requires a custom entry in the device tree, see alder.dtsi.

To see the curent state of the USB ports use netconf or CLI:
<pre>
admin@infix-00-01-00:/> show hardware 
USB PORTS           
NAME                STATE     
USB                 unlocked  
</pre>
The configuration of USB port state is done using ietf-hardware (with some additions)
<pre>
admin@infix-00-01-00:/> configure 
admin@infix-00-01-00:/config/> edit hardware 
admin@infix-00-01-00:/config/hardware/> set component USB class usb 
admin@infix-00-01-00:/config/hardware/> set component USB state admin-state locked 
admin@infix-00-01-00:/config/hardware/> leave 
admin@infix-00-01-00:/> 
</pre>

Also add USB stick on qemu machines, and a very simple test.

2024-02-19 21:41 UTC, wkz requested changes
Great job!

2024-02-19 21:41 UTC, wkz commented on src/confd/src/ietf-hardware.c
> +		return SR_ERR_OK;
Given that there is not really a way that `SR_EV_CHANGE` can fail, would it be easier to just return `SR_ERR_OK` from it, and then write the `authorized` files directly from confd from `SR_EV_DONE`? I.e. skip the script file and call `writedf()` from `usb_authorize()`/`dir_cb()`.

2024-02-19 21:41 UTC, wkz commented on src/confd/src/ietf-hardware.c
> +		(void)remove(SYSFS_CMDS);
If we do decide to keep the current construct with the script file, I think we always want to delete it here - even if `systemf()` fails.

2024-02-19 21:41 UTC, wkz commented on src/confd/src/ietf-hardware.c
> +	root = json_load_file("/run/system.json", 0, &error);
We parse this two times in this file. Will this show up in more places in the future? Then we might consider parsing it once and keeping it on the `struct confd`.

2024-02-19 21:41 UTC, wkz commented on src/confd/yang/infix-hardware@2024-01-18.yang
> +  }
Copypasta detected :robot: 

Even so...do we want to represent these as 3 distinct classes, or are they all of class `vpd`?

2024-02-19 21:41 UTC, wkz commented on test/case/ietf_hardware/usb.py
> +        assert(len(available) > 0)
```suggestion
        if len(available) < 1:
            test.skip()
```

2024-02-19 21:41 UTC, wkz commented on test/infamy/hardware.py
Do we think this will be used by any other tests?

If not, we might as well keep it close to the only user (i.e., in `usb.py`)

2024-02-23 09:59 UTC, wkz approved these changes
Looks great! :sparkles:

2024-02-23 10:08 UTC, troglobit approved these changes
Awesome work!

2024-02-23 13:01 UTC, merged