Refactor Confd Yang Modules Setup Script
kernelkit/infix pull request #485
Opened 2024-06-18 09:15 UTC by ahmkar94

These changes aim to improve the modularity and maintainability of our codebase, making it easier to manage and extend the YANG module setup process in the future.

2024-06-18 09:30 UTC, mattiaswal requested changes

2024-06-18 09:30 UTC, mattiaswal commented on utils/yang_modules_setup.sh
> +check_file_exists $MODULES_LIST_FILE_INTERFACES
The file should be as an input to the script example:
```
./yang_modules_setup.sh file-with-modules
```
And in confd, just call the script twice
```
yang_modules_setup.sh confd.inc
yang_modules_setup.sh interfaces.inc
```

2024-06-18 09:30 UTC, mattiaswal commented on utils/yang_modules_setup.sh
> +MODULES_LIST_FILE_CONFD=${MODULES_LIST_FILE:-$(dirname "$0")/yang_modules_confd.inc}
Didn't it work to have a variable called MODULES as before and use source on the file requested?

2024-06-18 16:53 UTC, mattiaswal approved these changes
Great work :fireworks:  :+1:

2024-06-18 16:54 UTC, merged

2024-06-18 17:09 UTC, troglobit commented
I'm not really happy with all the whitespace changes in this PR.  Lots of initial indent introduced in the .mk file that does not comply with Buildroot standards.

Also, I'm left a confounded with the move of logic from src/confd to package/confd.  Why can't we keep the internals of which modules are needed in src/confd?

2024-06-19 07:48 UTC, mattiaswal commented
> I'm not really happy with all the whitespace changes in this PR. Lots of initial indent introduced in the .mk file that does not comply with Buildroot standards.
> 
> Also, I'm left a confounded with the move of logic from src/confd to package/confd. Why can't we keep the internals of which modules are needed in src/confd?

The logic, what do you mean? The script itself has been moved to utils/ to make it nicer when calling from an external build, also remove all knowledge about containers etc from that feels right, with that in mind. The calling of the script has always been in confd.mk. Is it the .inc files you do not like in src/confd/, I can agree, it should be moved, it should be with the source code.

2024-06-19 07:48 UTC, ahmkar94 commented
I had a feeling that I shouldn't touch the indentations. I just wasn't used to see 'if' logic without indentations xD
But I'll make a quick followup commit (PR) on that, which will also include a minor update in the list for the yang_modules_confd.inc file (missing a module).

2024-06-19 09:00 UTC, troglobit commented
We've had parts of confd spread out all over the tree before, and it was very difficult to keep track of origin and use.  So we gathered the pieces and put them back into src/confd/ where they belong.

Think of it like this: if confd was an external project (not living in src/) with a base set of YANG models and tools to manage it, we'd use package/confd/ to integrate it into Infix and any Infix extensions would live in board/common/.

So yes, the .inc files should live in src/confd/, next setup.sh in the scripts/ sub-directory.

2024-06-19 09:07 UTC, ahmkar94 commented
Created a followup PR https://github.com/kernelkit/infix/pull/487

2024-06-20 05:46 UTC, troglobit commented
FYI: just merged main into my branch ... and I had zero (0!) conflicts?  Took me a while to realize, but in this PR, you forgot to remove the old `confd/scripts/setup.sh` :smile: 

No worries, I'll migrate my local changes of that script to the new and remove `confd/scripts/setup.sh` on my branch.

2024-06-20 08:25 UTC, ahmkar94 commented
> FYI: just merged main into my branch ... and I had zero (0!) conflicts? Took me a while to realize, but in this PR, you forgot to remove the old `confd/scripts/setup.sh` 😄
> 
> No worries, I'll migrate my local changes of that script to the new and remove `confd/scripts/setup.sh` on my branch.

Ohhhh... 
Thnx :-)