Add support for automounting USB disks
kernelkit/infix pull request #538
Opened 2024-07-10 09:41 UTC by troglobit

## Description

This PR adds support for automounting USB disks of VFAT or exFAT type.

## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [ ] Bugfix
  - [ ] Regression tests
  - [ ] ChangeLog updates (for next release)
- [X] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [X] Documentation added?
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2024-08-02 20:43 UTC, mattiaswal requested changes

2024-08-02 20:43 UTC, mattiaswal commented on board/x86_64/linux_defconfig
Why only on x86?

2024-08-03 09:49 UTC, troglobit commented on board/x86_64/linux_defconfig
I think you missed the aarch64 diff, [above](https://github.com/kernelkit/infix/pull/538/files#diff-f71d1891f682685d945c33b7af83d809b389c260f924d8707d65168201af8b7e).

I'll add ExFAT also for the RISC-V arch as soon as this branch is merged :-)

2024-08-03 13:05 UTC, mattiaswal commented
The only thing missing as I can see, is an autotest, but I can add it later.

2024-08-04 05:42 UTC, merged