Introduce Test Mode for Build
kernelkit/infix pull request #571
Opened 2024-08-21 15:12 UTC by ahmkar94

To support testing, the 'test-config.cfg' has been introduced in Infix. Additionally, a test mode for the running image is required for this configuration to be applied.

Basically the 'test-config' will only be generated and loaded when the device is in 'test-mode', which is determined by the presence of the '/mnt/aux/test-mode file'. However, placing this file via the Qeneth system proved to be inconvenient in the test environment. Therefore, the entire image is built in test mode, with the 'test-mode' file preloaded onto the disk image (specifically in the auxiliary partition).

To support this, a new variable, '(bool) DISK_IMAGE_TEST_MODE', has been introduced:
 * 'enabled': the image will be built in the test mode;
 * 'disabled': the image will be built in the standard mode.

2024-08-21 16:01 UTC, troglobit commented
Please reference #568, e.g., "Part of issue #568", in the commit message so we can tie it all together, and always write a neat *summary* (details and novels in commit messages) also for the pull request itself.

2024-08-21 20:00 UTC, wkz requested changes
Love how neat this came out. Great job! :clap: :clap:

2024-08-23 08:39 UTC, ahmkar94 commented
> Please reference #568, e.g., "Part of issue #568", in the commit message so we can tie it all together, and always write a neat _summary_ (details and novels in commit messages) also for the pull request itself.

Sure :) Thnx

2024-08-23 08:40 UTC, ahmkar94 commented on board/common/mkdisk.sh
> +while getopts "a:b:B:n:s:t:" opt; do
Done, thnx

2024-08-23 08:40 UTC, ahmkar94 commented on board/common/mkdisk.sh
> +    [ -f "$root/aux/test-mode" ] && rm "$root/aux/test-mode"
Thnx :)

2024-08-23 08:40 UTC, ahmkar94 commented on board/common/Config.in
> +	  test configurations or files needed for testing.
Expanded the description

2024-08-23 14:17 UTC, wkz approved these changes
Excellent!

If you rebase this on `kernelkit:main`, I think the build issues should go away, so that we can verify that we don't have any breaking changes.

2024-08-26 11:59 UTC, merged