src/confd: add the ability to change MotD in cli
kernelkit/infix pull request #7
Opened 2023-04-11 15:10 UTC by rical

# Pull Request
Not sure if this is even something we want? I did it mainly to learn and to test the work flow.
If this is indeed something we want then I intent to fix the duplication of the default value (in skel /etc/motd and in the confd C code).
I might also hook it into the `aug` framework, even tho it should never fail (TM) and "abort" seems to work as intended?

# Commit message
Add the ability to set and delete system MotD (Message Of The Day) using the cli.

So there's no staging concept (aug), if user issues "leave" the change takes immediate effect.

The default value is hard coded in two places, confd and the rootfs file /etc/motd. The intention is to fix this in upcoming patches.

Introduces:
exec> configure> set system motd STRING
exec> configure> delete system motd

2023-04-11 17:33 UTC, troglobit commented
First of all, Yes, this is something we want, and it's a great example to start with I think!

Now, there are a few things that I believe need to be fixed:

  1. The standard models must be kept as-is, extensions should be in separate yang file(s) that we load in (in this case) `ietf-system.c` and use the augment syntax.  See `ietf-ip.yang` for an example.  Also, even though we've decided to go with IETF, there's another world of YANG models there that might serve as inspiration https://github.com/openconfig/public/blob/master/release/models/system/openconfig-system.yang (syntax, description, and types used for validation come to mind.)
  2. You should add `switch (event)` in your callback so you don't regenerate the file multiple times (you'll get at least two events per change), this will also allow you to handle abort without too much effort, or like I did with `change_hostname()`, just ignore all events except DONE (last event) and just trust that recreating the file(s) work and validation is done by libyang.

Oh, and you don't need to remove the duplicate /etc/motd file.  Infix has three operating modes (selectable with the `setup` tool) and one is the native mode in which users edit /etc manually. These modes share the same rootfs.  Your default MOTD can be something like "To enter the CLI, type 'cli' at the shell prompt."  or "Remember to change your default password at first login.", something more geared towards NETCONF (operating mode) users.

Last, Augeas is a really cool project and for anything more complex it's super useful. However, it's perfectly OK to render all simple files manually like you've done (and I did with chrony.conf).  After all, we've got a lot of models to implement ... ;-)

2023-04-12 12:26 UTC, troglobit reviewed
Looks great, we just need to rebase+squash at merge.  Handing over to @wkz for final review.

2023-04-12 14:26 UTC, troglobit requested changes

2023-04-12 14:26 UTC, troglobit commented on src/confd/yang/ietf-system@2014-08-06.yang
> +    }
Please don't modify std models, squash with last commit.

2023-04-12 14:42 UTC, wkz approved these changes

2023-04-12 14:51 UTC, merged