test: Update topogies and test texts
kernelkit/infix pull request #710
Opened 2024-10-14 14:33 UTC by mattiaswal

All mgmt links should be lightgrey, all mgmt ports should be named mgmt links between duts should be named link.

## Description

## Other information

## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [ ] Bugfix
  - [ ] Regression tests
  - [ ] ChangeLog updates (for next release)
- [ ] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [ ] Documentation added?
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2024-10-14 14:35 UTC, troglobit commented
Wow, that was quick! Nice work :100:

2024-10-15 09:16 UTC, axkar requested changes
Great work! A few comments only :)

2024-10-15 09:43 UTC, jovatn approved these changes
Great work!
See inline comments for proposed fixes - use what you think is useful.

A related note: OSPF multi-area still does not explain 11.0-network in topology or description, but mentioned in one of the test steps. Perhaps a small note in description, saying there are additional networks?

2024-10-15 11:40 UTC, mattiaswal commented on test/case/ietf_interfaces/bridge_vlan/topology.dot
> +	    label="{ <mgmt> mgmt | <data> data | <link> lnk2} | dut1\n(10.0.0.2) ",
Of course :+1:

2024-10-15 11:43 UTC, mattiaswal commented on test/case/ietf_interfaces/dual_bridge/Readme.adoc
>  . Configure two bridges linked with a veth pair furthest bridge has IP 10.0.0.2
Redundant information, the IP is shown in ASCII art. Removing it

2024-10-15 12:10 UTC, axkar approved these changes
:1st_place_medal:

2024-10-15 12:11 UTC, mattiaswal commented on test/case/ietf_interfaces/bridge_vlan_separation/test.py
>  """
I agree :)

2024-10-16 09:01 UTC, mattiaswal commented
> Great work! See inline comments for proposed fixes - use what you think is useful.
> 
> A related note: OSPF multi-area still does not explain 11.0-network in topology or description, but mentioned in one of the test steps. Perhaps a small note in description, saying there are additional networks?

Forgot that! There is  now an ASCII-art over loopback configuration.

2024-10-16 09:24 UTC, merged