Expand mDNS settings
kernelkit/infix pull request #833
Opened 2024-11-24 22:35 UTC by troglobit

## Description

This PR adds support for modifying the following Avahi daemon settings:

 - `domain-name`
 - `allow-interfaces`
 - `deny-interfaces`
 - `enable-reflector`
 - `reflect-filters`

Also included, a review of the default `sysctl` settings, and some fixes and clarifications to the Networking Guide.

## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [ ] Bugfix
  - [ ] Regression tests
  - [ ] ChangeLog updates (for next release)
- [X] Feature
  - [X] YANG model change => revision updated?
  - [X] Regression tests added?
  - [x] ChangeLog updates (for next release)
  - [x] Documentation added?
- [ ] Test changes
  - [ ] Checked in changed Readme.adoc (make test-spec)
  - [ ] Added new test to group Readme.adoc and yaml file
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [ ] Documentation content changes
  - [ ] ChangeLog updated (for major changes)
- [ ] Other (please describe):

2024-12-03 18:32 UTC, troglobit commented
@mattiaswal + @jovatn this PR is now finished and awaiting your review.

2024-12-04 08:50 UTC, jovatn approved these changes
Update https://github.com/kernelkit/infix/blob/main/doc/discovery.md#mdns with (rudimentary) descriptions of available mdns settings.

sysctl updates looks good to me, but perhaps we could have an IRL session for rubber ducking on sysctl changes?

2024-12-04 10:32 UTC, troglobit commented on src/confd/yang/infix-services.yang
> +                     By defaullt all, except loopback and point-to-pint links.";
Ah, thanks!

2024-12-04 10:32 UTC, troglobit commented on src/confd/yang/infix-services.yang
> +                     By defaullt all services are reflected.";
Thanks!

2024-12-04 10:38 UTC, troglobit commented on src/confd/yang/infix-services.yang
> +        type boolean;
The default is disabled.  The rest of the team did not feel the reflector should be enabled by default on all products.

2024-12-04 11:49 UTC, mattiaswal requested changes

2024-12-04 11:49 UTC, mattiaswal commented on doc/ChangeLog.md
This should also contain the NTP fixes, merge errors?

2024-12-04 11:49 UTC, mattiaswal commented on src/confd/src/infix-services.c
> +		const char *hostnm = fgetkey("/etc/os-release", "DEFAULT_HOSTNAME");
Use hostname instead of hostnm pleeeeease.

2024-12-04 11:49 UTC, mattiaswal commented on test/case/infix_services/Readme.adoc
> +include::mdns_allow_deny/Readme.adoc[]
Add a blank line after the include

2024-12-04 11:54 UTC, troglobit commented on doc/ChangeLog.md
Ah, yes of course, nice catch!

2024-12-04 13:31 UTC, mattiaswal approved these changes
:100:

2024-12-04 14:01 UTC, merged